Fix Python3 SyntaxError
Python 3.6 emits the following error:

    File "/usr/lib/python3.6/site-packages/cooldict.py", line 577
      print da[10]
             ^
  SyntaxError: Missing parentheses in call to 'print'. Did you mean print(da[10])?

Address this by adding the suggested parentheses, here and in all comments.

Signed-off-by: Andreas Färber <afaerber@suse.de>